-- ==============================================================================
-- NETORA v2 - SKEMA DATABASE SUPABASE (POSTGRESQL)
-- Salin dan jalankan seluruh isi file ini di SQL Editor dashboard Supabase Anda.
-- ==============================================================================

-- 1. EXTENSIONS (Dukungan Ekstensi PostgreSQL)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. TABEL: users (Data Pengguna / Siswa & Administrator)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    password_plain VARCHAR(255),
    foto TEXT DEFAULT 'uploads/default.png',
    bio TEXT DEFAULT 'Siswa TKJ Antusias Belajar Jaringan',
    role VARCHAR(50) NOT NULL DEFAULT 'siswa',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index pencarian cepat berdasarkan email dan role
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);

-- ==============================================================================
-- 3. TABEL: materi (Katalog Modul Pembelajaran TKJ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.materi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    isi TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index filter materi berdasarkan kategori
CREATE INDEX IF NOT EXISTS idx_materi_kategori ON public.materi(kategori);

-- ==============================================================================
-- 4. TABEL: video (Galeri Vidio Praktikum Jaringan / YouTube)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.video (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT DEFAULT '',
    url_youtube TEXT NOT NULL,
    kategori VARCHAR(100) DEFAULT 'Mikrotik',
    durasi VARCHAR(50) DEFAULT '15:00',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index filter vidio berdasarkan kategori
CREATE INDEX IF NOT EXISTS idx_video_kategori ON public.video(kategori);

-- ==============================================================================
-- 5. TABEL: quiz (Bank Soal Kuis Pilihan Ganda Siswa)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pertanyaan TEXT NOT NULL,
    pilihan_a TEXT NOT NULL,
    pilihan_b TEXT NOT NULL,
    pilihan_c TEXT NOT NULL,
    pilihan_d TEXT NOT NULL,
    jawaban_benar CHAR(1) NOT NULL CHECK (jawaban_benar IN ('A', 'B', 'C', 'D')),
    kategori VARCHAR(100) NOT NULL DEFAULT 'Cisco Packet Tracer',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index pencarian soal per kategori
CREATE INDEX IF NOT EXISTS idx_quiz_kategori ON public.quiz(kategori);

-- ==============================================================================
-- 6. TABEL: nilai_quiz (Riwayat Hasil Ujian & Skor Kuis Siswa)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.nilai_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    skor INTEGER NOT NULL CHECK (skor >= 0 AND skor <= 100),
    tanggal TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index relasi siswa dan rentang skor (keperluan grafik & leaderboard)
CREATE INDEX IF NOT EXISTS idx_nilai_quiz_user_id ON public.nilai_quiz(user_id);
CREATE INDEX IF NOT EXISTS idx_nilai_quiz_skor ON public.nilai_quiz(skor);
CREATE INDEX IF NOT EXISTS idx_nilai_quiz_tanggal ON public.nilai_quiz(tanggal DESC);

-- ==============================================================================
-- 7. TABEL: pengumuman (Pusat Notifikasi & Info Sekolah)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.pengumuman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    isi TEXT NOT NULL,
    kategori VARCHAR(100) NOT NULL DEFAULT 'Pengumuman',
    penting SMALLINT NOT NULL DEFAULT 0, -- 1 = Penting/Prioritas, 0 = Biasa
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index notifikasi terbaru
CREATE INDEX IF NOT EXISTS idx_pengumuman_created ON public.pengumuman(created_at DESC);

-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS) - Kebijakan Keamanan Supabase
-- ==============================================================================
-- Aktifkan RLS pada seluruh tabel
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nilai_quiz ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengumuman ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses Baca Publik (Anonim & Authenticated bisa membaca modul, video, pengumuman)
CREATE POLICY "Akses publik baca materi" ON public.materi FOR SELECT USING (true);
CREATE POLICY "Akses publik baca video" ON public.video FOR SELECT USING (true);
CREATE POLICY "Akses publik baca pengumuman" ON public.pengumuman FOR SELECT USING (true);
CREATE POLICY "Akses publik baca quiz" ON public.quiz FOR SELECT USING (true);

-- Kebijakan Akses Backend Service Role (Bypass RLS untuk server backend Express)
-- Saat backend Express menggunakan SUPABASE_SERVICE_ROLE_KEY, backend memiliki akses penuh (CRUD) otomatis.

-- ==============================================================================
-- 9. DATA AWAL (SEEDING DATA)
-- ==============================================================================

-- A. Akun Default Administrator (Password: admin123)
-- Hash bcrypt 10 rounds untuk 'admin123': $2b$10$tZz2B5E2W2vN32r9yXqF9eQZfZjQy8y3gU4JpA6QY7YcZ...
INSERT INTO public.users (nama, email, password, role, bio)
VALUES (
    'Administrator Netora',
    'admin123',
    '$2a$10$7vY/7MqvYhC83Y7sS4sLReL.81nJbI6m.3m04l9iC2kR1q7kU7Q7a',
    'admin',
    'Pengelola Utama Platform Pembelajaran Siswa TKJ Netora'
)
ON CONFLICT (email) DO NOTHING;

-- B. Seeding Modul Materi Awal TKJ
INSERT INTO public.materi (judul, kategori, isi)
VALUES 
(
    'Dasar Jaringan & Topologi Cisco Packet Tracer',
    'Cisco Packet Tracer',
    'Cisco Packet Tracer adalah perangkat lunak simulasi jaringan visual buatan Cisco Systems yang memungkinkan siswa mensimulasikan topologi jaringan dan konfigurasi perangkat switch & router modern.

7 Lapisan OSI Model pada Perangkat Cisco:
1. Physical: Transmisi bit melalui kabel UTP (Straight / Cross) dan Fiber Optik.
2. Data Link: Pengalamatan MAC Address & pembentukan frame pada Switch Layer 2.
3. Network: Pengalamatan IP Address & Routing paket pada Router.
4. Transport: Pengiriman end-to-end (TCP/UDP).
5. Session: Manajemen sesi komunikasi antar host.
6. Presentation: Enkripsi, kompresi, & format data.
7. Application: Antarmuka layanan seperti HTTP, DNS, DHCP, dan FTP.'
),
(
    'Konfigurasi VLAN & Trunking pada Switch Cisco',
    'Cisco Packet Tracer',
    'Virtual Local Area Network (VLAN) memungkinkan pembagian broadcast domain pada switch yang sama secara logis untuk meningkatkan efisiensi dan keamanan jaringan.

Command Dasar Konfigurasi VLAN di Cisco IOS (Packet Tracer):
Switch# configure terminal
Switch(config)# vlan 10
Switch(config-vlan)# name LAB_TKJ_1
Switch(config-vlan)# exit
Switch(config)# interface fastEthernet 0/1
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10

Untuk port penghubung antar Switch (Trunk Link):
Switch(config)# interface fastEthernet 0/24
Switch(config-if)# switchport mode trunk
Switch(config-if)# switchport trunk allowed vlan 10,20'
),
(
    'Pengenalan RouterOS & Konfigurasi Dasar Mikrotik',
    'Mikrotik',
    'MikroTik RouterOS adalah sistem operasi berbasis Linux yang diperuntukkan sebagai router jaringan handal untuk manajemen bandwidth, routing, hotspot, dan firewall.

Langkah Dasar Konfigurasi MikroTik:
1. Hubungkan port Ether1 ke sumber Internet (DHCP Client).
2. Konfigurasi IP Address lokal pada Ether2 (contoh: 192.168.10.1/24).
3. Buat NAT Masquerade agar client lokal bisa mengakses internet:
   /ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade
4. Konfigurasi DNS Server (contoh: 8.8.8.8) dan centang Allow Remote Requests.
5. Konfigurasi DHCP Server untuk membagikan IP otomatis ke komputer siswa.'
),
(
    'Manajemen Bandwidth Simple Queue & Queue Tree Mikrotik',
    'Mikrotik',
    'Manajemen bandwidth di MikroTik digunakan untuk membagi dan membatasi kecepatan download dan upload tiap komputer client agar pemakaian bandwidth adil dan stabil.

1. Simple Queue:
Cocok untuk skala kecil dan pemula. Membatasi bandwidth berdasarkan target IP Address secara langsung:
/queue simple add name=Client-TKJ target=192.168.10.50/32 max-limit=5M/10M

2. Queue Tree:
Cocok untuk jaringan sekolah skala menengah hingga besar dengan pembagian hierarki Parent-Child yang presisi berdasarkan Packet Mark dari IP Firewall Mangle.'
),
(
    'Administrasi Linux Server (Debian/Ubuntu) & SSH Remote',
    'Server & Linux',
    'Linux Server merupakan fondasi utama infrastruktur IT modern seperti Web Server, DNS Server, Database, dan Cloud Computing.

Perintah Esensial Administrasi Linux:
- sudo apt update && sudo apt upgrade : Memperbarui repositori & paket sistem
- systemctl status nginx : Memeriksa status service web server
- sudo ufw allow 22/tcp : Mengizinkan port SSH pada firewall
- ssh siswa@192.168.1.10 -p 22 : Melakukan remote shell secara aman

Selalu terapkan praktik keamanan dengan mematikan akses login root langsung melalui SSH.'
),
(
    'Instalasi & Konfigurasi Web Server Nginx di Linux',
    'Server & Linux',
    'Nginx adalah web server berperforma tinggi yang terkenal ringan dan memiliki arsitektur asynchronous event-driven untuk menangani ribuan koneksi secara simultan.

Langkah Instalasi & Setup Nginx:
1. sudo apt install nginx -y
2. systemctl start nginx && systemctl enable nginx
3. Konfigurasi Virtual Host / Server Block di /etc/nginx/sites-available/default:
   server {
       listen 80;
       server_name netora.local;
       root /var/www/html;
       index index.html index.htm;
   }
4. sudo nginx -t && sudo systemctl reload nginx'
);

-- C. Seeding Video Tutorial Awal
INSERT INTO public.video (judul, deskripsi, url_youtube, kategori, durasi)
VALUES 
(
    'Simulasi & Praktikum Jaringan Cisco Packet Tracer untuk Pemula',
    'Panduan langkah demi langkah merancang topologi, routing dasar, dan VLAN switch di Cisco Packet Tracer.',
    'https://www.youtube-nocookie.com/embed/qiQR5rTSshw?rel=0&modestbranding=1',
    'Cisco Packet Tracer',
    '22:15'
),
(
    'Tutorial Dasar Konfigurasi Mikrotik RB750r2 untuk Pemula',
    'Panduan langkah demi langkah menyetting Mikrotik dari kondisi reset hingga terkoneksi internet.',
    'https://www.youtube-nocookie.com/embed/IPvYjXCsTg8?rel=0&modestbranding=1',
    'Mikrotik',
    '18:40'
),
(
    'Cara Setup Bandwidth Management & Hotspot Server Mikrotik',
    'Pelajari cara mengaktifkan fitur Hotspot Mikrotik lengkap dengan manajemen bandwidth Simple Queue.',
    'https://www.youtube-nocookie.com/embed/M7lc1UVf-VE?rel=0&modestbranding=1',
    'Mikrotik',
    '25:10'
);
